{{- if .Values.service.reportCenter.ingress.enabled -}}
{{ if .Values.service.reportCenter.ingress.interface }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "{{ .Values.namespace }}"
  name: {{ .Values.dipModule }}-{{ .Values.cluster }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "500M"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
{{- if .Values.service.ingressclassname }}
  ingressClassName: "{{.Values.service.ingressclassname}}"
{{- end }}
  rules:
  - http:
      paths:
        {{- range .Values.service.reportCenter.ingress.interface.path }}
        - path: {{ . }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ $.Values.dipModule }}-{{ $.Values.cluster }}
              port:
                number: {{ $.Values.service.reportCenter.port }}
        {{- end }}
{{ end }}
{{- end }}
